### ISSUE TITLE
[BUG] Drag and drop Error (Illegal invocation)

### ISSUE THREAD

**Issue by ErrorBot1122** [zenozeng/p5.js-svg#202]
When I try to add the drop method to the canvas It gives me an `Illegal invocation` error.

```console
TypeError: Cannot read properties of undefined (reading 'functionName')
    at undefined:60163:72

TypeError: Illegal invocation
    at addEventListener (https://unpkg.com/p5.js-svg@1.1.1/node_modules/svgcanvas/dist/svgcanvas.js:1410:37)

    at RendererSVG._main.default.Element.drop (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:75131:26)

    at setup (/sketch.js:9:7)

    at _setup (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:62985:27)

    at _runIfPreloadsAreDone (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:62922:29)

    at p5._decrementPreload (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js:62932:27)

    at p5.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/addons/p5.sound.min.js:2:98292)
```

I think a potential fix is putting a `div` on top to the canvas and then mapping all the drop, click, running the callback function from there

**Code ( Simple ):**
```js
function onDrop() {
	console.log("IT WORKS?!?!?!?!?")
}

function setup() {
  let cnv = createCanvas(windowWidth, windowHeight, SVG);
  background(220)
  
  cnv.drop(onDrop) // Wont work...
 }
```

Code Example: **[P5 Editor,](https://editor.p5js.org/Errorbot_1122_School/sketches/Quo6dpXn_) [JFiddle](https://jsfiddle.net/Errorbot1122/qfpLr5u7/1/)**

**Comment by zenozeng** [comment]
@ErrorBot1122 Thanks for reporting this bug, it should be fixed with p5.js-svg@1.3.1.

**Comment by ErrorBot1122** [comment]
:)
