### ISSUE TITLE
Incompatible with P5.js version 1.7.0 and 1.8.0

### ISSUE THREAD

**Issue by bcorporaal** [zenozeng/p5.js-svg#254]
If I try to use p5.js-svg with a newer version of p5.js (1.7.0 and 1.8.0) I get the following error message:
`Uncaught TypeError: this.drawingContext is undefined`

When I switch back the p5 version to 1.6.0, everything is fine. An easy way to test is is to use the example page from this repository and try different versions of p5.js.

The full message I get in Firefox is:
```
Uncaught TypeError: this.drawingContext is undefined
    resize https://unpkg.com/p5.js-svg@1.5.1:1646
    createCanvas https://unpkg.com/p5.js-svg@1.5.1:2012
    setup http://127.0.0.1:5500/examples/lib/demo.js line 31 > eval:3
    _setup https://unpkg.com/p5@1.7.0/lib/p5.js:61891
    _start https://unpkg.com/p5@1.7.0/lib/p5.js:61826
    p5 https://unpkg.com/p5@1.7.0/lib/p5.js:62131
    onload http://127.0.0.1:5500/examples/lib/demo.js:32
    route http://127.0.0.1:5500/examples/lib/demo.js:22
    <anonymous> http://127.0.0.1:5500/examples/lib/demo.js:38
p5.js-svg@1.5.1:1646:17
    resize https://unpkg.com/p5.js-svg@1.5.1:1646
    createCanvas https://unpkg.com/p5.js-svg@1.5.1:2012
    setup http://127.0.0.1:5500/examples/lib/demo.js line 31 > eval:3
    _setup https://unpkg.com/p5@1.7.0/lib/p5.js:61891
    _start https://unpkg.com/p5@1.7.0/lib/p5.js:61826
    p5 https://unpkg.com/p5@1.7.0/lib/p5.js:62131
    onload http://127.0.0.1:5500/examples/lib/demo.js:32
    (Async: EventHandlerNonNull)
    route http://127.0.0.1:5500/examples/lib/demo.js:22
    <anonymous> http://127.0.0.1:5500/examples/lib/demo.js:38
```
I get a similar error message in Chrome:
```
p5.js-svg@1.5.1:1646 Uncaught TypeError: Cannot read properties of undefined (reading '__clearCanvas')
    at RendererSVG.RendererSVG.resize (p5.js-svg@1.5.1:1646:37)
    at Rendering.p5.createCanvas (p5.js-svg@1.5.1:2012:32)
    at setup (eval at req.onload (demo.js:31:9), <anonymous>:3:5)
    at p5._setup (p5.js:61891:25)
    at p5._start (p5.js:61826:23)
```

And Safari:
```
[Error] TypeError: undefined is not an object (evaluating 'this.drawingContext.__clearCanvas')
	(anonymous function) (p5.svg.js:1646)
	(anonymous function) (p5.svg.js:2012)
	setup (Anonymous Script 1 (line 3))
	(anonymous function) (p5.js:61891)
	(anonymous function) (p5.js:61826)
	p5 (p5.js:62131)
	(anonymous function) (demo.js:32)

```

**Comment by BernhardPoppe** [comment]
I can confirm this :/

**Comment by MichaelRexSchumacher** [comment]
Same here. 
![image](https://github.com/zenozeng/p5.js-svg/assets/3431290/ed73286d-fb1b-441d-a706-f7ff8f719b25)

**Comment by golanlevin** [comment]
Just confirming that this error is still the case for p5.js v.1.9.0.

**Comment by CampbellOwen** [comment]
I'm not a javascript expert, but it appears this may be due to a difference in how the p5 source is bundled? The `Renderer2D` constructor now now longer directly mutates `this` as it did before:
```javascript

function Renderer2D(elt, pInst, isMainCanvas) {
  var _this;
  _classCallCheck(this, Renderer2D);
  _this = _super.call(this, elt, pInst, isMainCanvas);
  _this.drawingContext = _this.canvas.getContext('2d');
  _this._pInst._setProperty('drawingContext', _this.drawingContext);
  return _this;
}
``` 

It works for me locally if in the file `p5.RendererSVG.ts` you change [line 50](https://github.com/zenozeng/p5.js-svg/blob/553c2b28a9309de98f333364b980f7c7d6bfaaf9/src/p5.RendererSVG.ts#L50) from 

```typescript
p5.Renderer2D.call(this, elt, pInstProxy, isMainCanvas)
```
to
```typescript
Object.assign(this, p5.Renderer2D.call(this, elt, pInstProxy, isMainCanvas))
```

**Comment by nkymut** [comment]
Awesome, the change you suggested works on the editor.p5js.org with p5.js v.1.9.0 too - woo hoo🎉
https://editor.p5js.org/didny/sketches/-fk-owhPp

**Comment by lostPixels** [comment]
Confirmed working locally with p5.js v1.9.0 as well.

**Comment by xanderjl** [comment]
I'm curious if someone would be willing to publish their fork with this working change. I tried the same patch locally and published it to npm, but it wasn't performing as expected in my project 👀

**Comment by bcorporaal** [comment]
@xanderjl I have not forked it but if it helps, I have included a patched version in my [Toko framework](https://github.com/bcorporaal/Toko). That one works fine with p5.js v1.9.0.

**Comment by psicomante** [comment]
Hi guys, 

I tried your fix and it's works just on `p5.createCanvas` but not on `p5.createGraphics`. I get the same error of @nkymut.

**Comment by zenozeng** [comment]
Compatibility with p5.js 1.11.x is now fixed in p5.js-svg v1.6.0.
Feel free to check out the [release notes](https://github.com/zenozeng/p5.js-svg/releases/tag/v1.6.0) for details.

**Comment by bcorporaal** [comment]
@zenozeng Thank you for updating p5.js-svg and also starting work on compatibility with P5.js 2. SVGs and your work are integral to some of my projects, so your effort is much appreciated! 🙏
