### ISSUE TITLE
Examples are broken 

### ISSUE THREAD

**Issue by rybarczykj** [zenozeng/p5.js-svg#255]
none of the canvases at https://zenozeng.github.io/p5.js-svg/examples/ are rendering.

console errors say 

```
VM419:2 Uncaught ReferenceError: SVG is not defined
    at setup (eval at req.onload (demo.js:31:9), <anonymous>:2:28)
    at p5._setup (p5.js:64079:27)
    at p5._start (p5.js:64002:25)
    at new p5 (p5.js:64355:22)
    at req.onload (demo.js:32:9)
```

**Comment by dkyy** [comment]
I'm having the same problem.

**Comment by pifragile** [comment]
i found this to be an issue with versioning. this setup worked for me:
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.0/p5.min.js"></script>
  <script src="https://unpkg.com/p5.js-svg@1.3.1"></script>
```

**Comment by spencerflem** [comment]
Seeing the same thing:
It's making a request to https://zenozeng.github.io/p5.js-svg/dist/p5.svg.js which 404's

**Comment by zenozeng** [comment]
Fixed in p5.js-svg v1.6.0. Feel free to check out the [release notes](https://github.com/zenozeng/p5.js-svg/releases/tag/v1.6.0) for details.
