### ISSUE TITLE
TypeError: Cannot read property '1' of null in bezierPoint's unit test

### ISSUE THREAD

**Issue by zenozeng** [zenozeng/p5.js-svg#49]
in bezierPoint's unit test:

```
TypeError: Cannot read property '1' of null
    at ctx.__applyStyleToCurrentElement (http://localhost:8000/dist/p5.svg.js:338:47)
    at ctx.stroke (http://localhost:8000/dist/p5.svg.js:578:22)
    at methods.forEach._this.(anonymous function) [as stroke] (http://localhost:8000/dist/p5.svg.js:985:35)
    at eval (eval at <anonymous> (test-render.js?_=1432915454074:44:22), <anonymous>:10:32)
    at test-render.js?_=1432915454074:44:17
    at Array.forEach (native)
    at _testRender (test-render.js?_=1432915454074:34:27)
    at HTMLDocument.<anonymous> (test-render.js?_=1432915454074:172:13)
```

**Comment by zenozeng** [comment]
```javascript
                noFill();
                bezier(85, 20, 10, 10, 90, 90, 15, 80);
                fill(255);
                steps = 10;
                for (var i = 0; i <= steps; i++) {
                    var t = i / steps;
                    x = bezierPoint(85, 10, 90, 15, t);
                    y = bezierPoint(20, 10, 90, 80, t);
                    stroke(100); // this line fix it!
                    ellipse(x, y, 5, 5);
                }
```

**Comment by zenozeng** [comment]
Seems that in `__applyStyleToCurrentElement`, it tries to set strokeStyle to rgba(NaN,NaN,NaN,1), 
So, the following code fails:
```javascript
                                regex = /rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d?\.?\d*)\s*\)/gi;
                                matches = regex.exec(value);
                                this.__currentElement.setAttribute(style.svgAttr, format('rgb({r},{g},{b})', {
                                    r: matches[1],
                                    g: matches[2],
                                    b: matches[3]
                                }));
```

**Comment by zenozeng** [comment]
```javascript
  p5.prototype.stroke = function() {
    this._setProperty('_doStroke', true);
    var ctx = this.drawingContext;
    var color = this.color.apply(this, arguments);
    ctx.strokeStyle = color.toString();
  };
``

**Comment by zenozeng** [comment]
```javascript
  p5.prototype.curve = function(x1, y1, x2, y2, x3, y3, x4, y4) {
    if (!this._doStroke) {
      return;
    }
    this.beginShape();
    this.curveVertex(x1, y1);
    this.curveVertex(x2, y2);
    this.curveVertex(x3, y3);
    this.curveVertex(x4, y4);
    this.endShape();
    this.stroke(); // note this line
    return this;
  };
```

**Comment by zenozeng** [comment]
It's strange that it call this.stroke() at last, which make current strokeStyle mess.

**Comment by zenozeng** [comment]
In latest p5.js:

![2015-05-31 13 10 15](https://cloud.githubusercontent.com/assets/2544489/7900634/71f13eca-0796-11e5-9102-ca4d70c96dea.png)

**Comment by zenozeng** [comment]
However, we should check the behavior of Canvas, and throw a readable exception if try to set strange strokeStyle

**Comment by zenozeng** [comment]
https://github.com/zenozeng/svgcanvas/commit/2c6350842957d451a30d4466e5007a6876399819

**Comment by zenozeng** [comment]
Still having the same bug in 0.4.5, maybe waiting for 0.4.6, there are a lot of commits since 0.4.5.

**Comment by zenozeng** [comment]
Should be fixed in https://github.com/zenozeng/svgcanvas/commit/9a673002f5212d231707389d78d5012bb06db8b6
